# Generated by Django 4.1.1 on 2022-11-10 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conserje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Fono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('NRO', models.IntegerField(primary_key=True, serialize=False)),
                ('Owner', models.CharField(max_length=50)),
                ('Telefono', models.IntegerField()),
                ('Mail', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_recepcion', models.DateField(blank=True, null=True)),
                ('remitente', models.CharField(max_length=50)),
                ('destinatario', models.CharField(max_length=50)),
                ('NroResidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.residencia')),
                ('conserje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conserje')),
            ],
        ),
    ]
